# Generated by Django 5.2.12 on 2026-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lattice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crystal_system', models.CharField(choices=[('triclinic', 'Триклинная'), ('monoclinic', 'Моноклинная'), ('orthorhombic', 'Ромбическая'), ('tetragonal', 'Тетрагональная'), ('rhombohedral', 'Ромбоэдрическая'), ('hexagonal', 'Гексагональная'), ('cubic', 'Кубическая')], max_length=20, verbose_name='Сингония')),
                ('lattice_type', models.CharField(choices=[('P', 'Примитивная (P)'), ('C', 'Базоцентрированная (C)'), ('I', 'Объемно-центрированная (I)'), ('F', 'Гранецентрированная (F)')], max_length=1, verbose_name='Тип решетки')),
                ('image_name', models.CharField(max_length=100, verbose_name='Имя файла изображения')),
            ],
            options={
                'verbose_name': 'Решетка Браве',
                'verbose_name_plural': 'Решетки Браве',
                'unique_together': {('crystal_system', 'lattice_type')},
            },
        ),
    ]
